run:
	@(cd PanicGrip; make $@)

debug:
	@(cd PanicGrip; make $@)

devices:
	@(cd PanicGrip; make $@)

doctor:
	@(cd PanicGrip; make $@)

studio:
	@(cd PanicGrip; make $@)

all:run


r:run
d:devices
doc:doctor
s:studio
