run:
	flutter run --release

debug:
	flutter run

devices:
	flutter devices

doc:
	flutter doctor -v

studio:
	/home/averma/work/panicgrip/android-studio/bin/studio.sh

all:run

r:run
d:devices
doc:doctor
s:studio
