run:
	flutter run --release

debug:
	flutter run

devices:
	flutter devices

doctor:
	flutter doctor -v

studio:
	/home/averma/work/panicgrip/android-studio/bin/studio.sh

all:run

stt:debug
tts:debug

vim:
	export EDITOR=vim
	@echo vim lib/main.dart
	vim lib/main.dart

vic:
	export EDITOR=vim
	@echo vim lib/processCamera.dart
	vim lib/processCamera.dart

vil:
	export EDITOR=vim
	@echo vim lib/processLocation.dart
	vim lib/processLocation.dart

vif:
	export EDITOR=vim
	vim lib/processFlashlight.dart

vis:
	export EDITOR=vim
	vim lib/processSettings.dart

via:
	export EDITOR=vim
	vim lib/processAlarm.dart

r:run
d:devices
doc:doctor
s:studio
